namespace GlobalEnums
{
	public enum GamepadType
	{
		NONE = 0,
		UNKNOWN = 1,
		XBOX_ONE = 2,
		XBOX_360 = 3,
		PS4 = 4,
		PS_VITA = 5,
		WII_U_GAMEPAD = 6,
		WII_U_PRO_CONTROLLER = 7,
		PS3_WIN = 8,
		SWITCH_JOYCON_DUAL = 9,
		SWITCH_PRO_CONTROLLER = 10,
		PS5 = 11,
		XBOX_SERIES_X = 12,
		STEAM_DECK = 13,
		SWITCH2_JOYCON_DUAL = 14,
		SWITCH2_PRO_CONTROLLER = 15
	}
}
